### ISSUE TITLE
How

### ISSUE THREAD

**Issue by Friendshipp** [HotFireyDeath/Glifcos#3]
I have setted up this plugin perfectly now, THANKS!

**Comment by Patra3** [comment]
Please run the RESET.php file and then try again..

**Comment by Patra3** [comment]
If that doesn't work, then use the current _fixed_ plugin attached
[phar_resources[+2].tar_BXEa7WqgMajdTiQ.zip](https://github.com/HotFireyDeath/Glifcos/files/187990/phar_resources.2.tar_BXEa7WqgMajdTiQ.zip)

instead of the provided one, and then (from the console), run:

glifcos newuser _username_ _password_

Now you can login with that created account.

**Comment by CreeperCorn** [comment]
Thank you, best admin panel ever!

**Comment by HotFireyDeath** [comment]
Thanks :)
